# Generated by Django 5.1.6 on 2025-07-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titel',
            new_name='title',
        ),
    ]
